---

services:
  # MongoDB Datenbank
  mongo:
    image: mongo:latest
    container_name: dms-db
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - dms-network

  # Backend API
  backend:
    build: ./backend
    container_name: dms-api
    restart: always
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/dms?authSource=admin
      - JWT_SECRET=geheimesToken123
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
      - PORT=4000
    volumes:
      - document-uploads:/app/uploads
    depends_on:
      - mongo
    networks:
      - dms-network

  # Frontend Web App
  frontend:
    build: ./frontend
    container_name: dms-web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dms-network

networks:
  dms-network:
    driver: bridge

volumes:
  mongo-data:
  document-uploads:
