---

services:
  # MongoDB Datenbank
  mongo:
    image: mongo:latest
    container_name: dms-db
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 9WVTUg8zAdiKPoDL
    networks:
      - dms-network

  # Backend API
  backend:
    # Hier verwenden wir ein Image anstatt build
    image: dms-backend
    build:
      context: /opt/dms/backend
    container_name: dms-api
    restart: always
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://root:9WVTUg8zAdiKPoDL@mongo:27017/dms?authSource=admin
      - JWT_SECRET=jyCWn2Kk6RNaPpM9
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
      - PORT=4000
    volumes:
      - document-uploads:/app/uploads
    depends_on:
      - mongo
    networks:
      - dms-network

  # Frontend Web App
  frontend:
    # Hier verwenden wir ein Image anstatt build
    image: dms-frontend
    build:
      context: /opt/dms/frontend
    container_name: dms-web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dms-network

networks:
  dms-network:
    driver: bridge

volumes:
  mongo-data:
  document-uploads:
