version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: dms-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=dms
    restart: unless-stopped
    networks:
      - dms-network

  backend:
    build: ./backend
    container_name: dms-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - dms-uploads:/app/uploads
    environment:
      - MONGO_URI=mongodb://mongodb:27017/dms
      - JWT_SECRET=your-jwt-secret-key-change-in-production
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - dms-network

  frontend-builder:
    build:
      context: ./frontend
      dockerfile: Dockerfile.builder
    container_name: dms-frontend-builder
    volumes:
      - ./frontend:/app
      - frontend-build:/app/build
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://backend:4000
      - NODE_ENV=production
    networks:
      - dms-network

  frontend:
    image: nginx:alpine
    container_name: dms-frontend
    ports:
      - "80:80"
    volumes:
      - frontend-build:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend-builder
      - backend
    restart: unless-stopped
    networks:
      - dms-network

volumes:
  mongodb-data:
  dms-uploads:
  frontend-build:

networks:
  dms-network:
    driver: bridge
